### ISSUE TITLE
how to use one more variable inside 

### ISSUE THREAD

**Issue by ns-ajith** [cdgriffith/Box#213]
Currently, i use 

`yaml`
```
foo:
  something:
        fishy:
             a: b
             c: d
   test:
              f: h
              h: k

```

```
config = Box(hiyapyco.load('config/lambda.yaml', 'config/' + environment + '.yaml', method=hiyapyco.METHOD_MERGE,
                                               interpolate=True, failonmissingfiles=True))

```

if I do
```
name = os.getenv(name)   # that is something or test
print (config.name.fishy.a)
```
How can I use the variable `name` in the print function?

Sorry if it's a dump question I'm new to python
